export class FraudScorer {
  /**
   * Calculate overall Fraud Score, Confidence Score & Risk Tier from risk flags
   * @param {Array} riskFlags Array of risk flags generated by inspectors
   * @returns {Object} Final fraud score assessment
   */
  static evaluate(riskFlags = []) {
    let accumulatedFraudPoints = 0;
    let confidencePenaltyTotal = 0;

    riskFlags.forEach(flag => {
      accumulatedFraudPoints += flag.fraudScoreContribution || 0;
      confidencePenaltyTotal += flag.confidencePenalty || 0;
    });

    // Fraud Score bounded between 0% and 100%
    const rawFraudScore = Math.min(100, accumulatedFraudPoints);
    const fraudScore = Math.max(0, Math.round(rawFraudScore));

    // Confidence Score bounded between 0% and 100%
    const baseConfidence = 98;
    const confidenceScore = Math.max(50, Math.min(100, Math.round(baseConfidence - confidencePenaltyTotal)));

    let riskTier = 'LOW_RISK'; // SAFE
    let recommendation = 'ACCEPT';

    if (fraudScore >= 50) {
      riskTier = 'HIGH_RISK';
      recommendation = 'REJECT';
    } else if (fraudScore >= 20) {
      riskTier = 'MEDIUM_RISK';
      recommendation = 'MANUAL_REVIEW';
    }

    return {
      fraudScore,
      confidenceScore,
      riskTier,
      recommendation,
      isAuthentic: fraudScore < 20,
      totalAnomaliesDetected: riskFlags.length,
      riskFlags
    };
  }
}
