export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};

export const VERIFICATION_STATUS = {
  AUTHENTIC: 'AUTHENTIC',
  SUSPICIOUS: 'SUSPICIOUS',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
};

export const API_KEY_STATUS = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED'
};

export const SUBSCRIPTION_TIERS = {
  FREE: 'FREE',
  STARTER: 'STARTER',
  PRO: 'PRO',
  ENTERPRISE: 'ENTERPRISE'
};

export const TIER_LIMITS = {
  FREE: {
    MONTHLY_VERIFICATIONS: 100,
    RATE_LIMIT_PER_MIN: 30,
    MAX_API_KEYS: 1,
    PRICE_USD: 0,
    PRICE_INR: 0
  },
  STARTER: {
    MONTHLY_VERIFICATIONS: 1000,
    RATE_LIMIT_PER_MIN: 120,
    MAX_API_KEYS: 3,
    PRICE_USD: 29,
    PRICE_INR: 2499
  },
  PRO: {
    MONTHLY_VERIFICATIONS: 10000,
    RATE_LIMIT_PER_MIN: 300,
    MAX_API_KEYS: 10,
    PRICE_USD: 99,
    PRICE_INR: 7999
  },
  ENTERPRISE: {
    MONTHLY_VERIFICATIONS: 100000,
    RATE_LIMIT_PER_MIN: 1000,
    MAX_API_KEYS: 50,
    PRICE_USD: 299,
    PRICE_INR: 24999
  }
};
